local lib = loadstring(game:HttpGet("https://raw.githubusercontent.com/SaijiKung/Mexuit/main/Console%20Lib",true))();
local UI = lib.new("Console Library")
local Page = UI.Page("Hi")
local Page2 = UI.Page("Hello")
Page.toggle("autofarm",true,print)
Page.call("Hello",function()
   print("called")
end)
Page2.str("some_str","ayo",function(str)
   print("some str changed to "..str)
end)
Page2.int("some_int",0,100,50,function(int)
   print("some int changed to "..int)
end)
Page2.list("some_list",{"Gamers","Bobux"},"Gamers",function(list)
   print("some list changed to "..list)
end)

Page.show()
